# Site settings
title: Blog MesProspects.net
email: bonjour@firmapi.com
description: "Des conseils concrets et des ressources pour réussir votre prospection et faire croître votre activité."
baseurl:
url: http://blog.firmapi.com

# Build settings
# markdown: kramdown
permalink: /:title/
exclude: ["vendor"]

# Pour les tags
tag_page_layout: tag
tag_page_dir: category
tag_permalink_style: pretty